version: '3'

services:
  server:
    build:
      context: .
    hostname: "redirector.local"
    networks:
      - redirector
      - "Generic network"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

networks:
  redirector:
    driver: bridge
  "Generic network":
    external: true